source: "2018"
title: RSE International Survey
remote_theme: pmarsceill/just-the-docs
description: >- # this means to ignore newlines until "baseurl:"
  International Research Software Engineering survey
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://softwaresaved.github.io/international-survey-analysis"

theme: just-the-docs
search_enabled: true
color_scheme: survey

collections:
  section:
    permalink: "/:collection/:path/"
    output: true

kramdown:
  toc_levels: 2..2

just_the_docs:
  collections:
    section:
      name: Section
      nav_exclude: false
      search_exclude: false
